services:
  - type: web
    name: url-shortener-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /v1/api/url/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.onrender.com
